name: xomxv
channels:
- defaults
- conda-forge
dependencies:
- python=3.9.1
- pip>=20.3.3
- conda>=4.10.3
- pip:
    - argparse>=1.1
    - pandas>=1.3.0
    - numpy>=1.21.1
    - scipy>=1.4.1
    - matplotlib>=3.4.2
    - torch>=1.7.1
    - scikit-learn>=0.24.2
    - joblib>=1.0.1
    - requests>=2.25.1
    - leidenalg>=0.8.8
    - umap-learn>=0.5.2
    - logomaker
