name:
channels:
- conda-forge
dependencies:
- python>=3.9,<3.11
- pip>=21.3.1
- conda>=4.11.0
- pandas>=1.3.0
- numpy>=1.21.1
- anndata>=0.7.6
- scipy>=1.4.1
- matplotlib>=3.1.3
- scikit-learn>=0.24.2
- joblib>=1.0.1
- requests>=2.23.0
- holoviews>=1.17.1
- bokeh>=3.2.2
- jax>=0.3.23
- pip:
    - leidenalg>=0.8.8
    - optax>=0.1.2
    - flax>=0.6.3
